### ISSUE TITLE
CI: cilium_tls_http_integration_test failure

### ISSUE THREAD

**Issue by sayboras** [cilium/proxy#139]
### Description

The below run is failed without any related change. This is mainly due to multiple jobs running in parallel, the workaround is to run with job limit to 1. So there could be overlapping resources between the tests.

```bash
bazel  test --platforms=//bazel:linux_x86_64 --config=release --jobs=1 --test_timeout=300 --test_output=errors //tests/...
```

https://github.com/cilium/proxy/actions/runs/4272080973/jobs/7439190389
[logs_1256.zip](https://github.com/cilium/proxy/files/10868372/logs_1256.zip)
```
#14 350.1 //tests:cilium_tls_tcp_integration_test                                  PASSED in 3.6s
#14 350.1 //tests:cilium_websocket_codec_integration_test                          PASSED in 2.8s
#14 350.1 //tests:cilium_websocket_decap_integration_test                          PASSED in 0.4s
#14 350.1 //tests:cilium_websocket_encap_integration_test                          PASSED in 2.6s
#14 350.1 //tests:cilium_tls_http_integration_test                                 FAILED in 10.7s
```

**Comment by jrajahalme** [comment]
I've had this happen locally, file system watcher can't open socket, claims too many open files. I triaged this locally, files were in different directories, so that should not be the problem. We only use file system watcher for xDS in tests, so making the tests execute one at a time is a good workaround. Let's make sure we build them first with more parallel jobs in all cases, though.
