### ISSUE TITLE
Building cilium proxy from latest release branch of envoy

### ISSUE THREAD

**Issue by smijolovic** [cilium/proxy#32]
I noticed a PR for updating cillium-envoy to 1.15.0, but envoy is now at 1.16.1 release.

The latest build of cilium-envoy looks like its pulling 1.14.5 envoy. Would it be possible to modify this repo to allow the developer to pull specific release branches of envoy and add the cilium filters...or just use the native envoy proxy?

**Comment by smijolovic** [comment]
I found the way to do some of that mods and testing...but the challenge is obtaining the SHA256 hash of the release build. The SHA1 hash is straightforward.

How do you obtain the SHA256 hashes of the envoy repo?

**Comment by jrajahalme** [comment]
Unfortunately Envoy releases tend to not always be source-code compatible with the Cilium filters. Sometimes this is due to some changes in the actual filter interfaces, but more often due to some Envoy internal changes we depend on at the source code leval (e.g., gRPC subscriptions). We also need to maintain sync with Istio, and in general we'll update master to the next Envoy release first, then update our Istio support to the next version that depends on the same general Envoy release. With this approach we minimize Cilium filter source code changes we need to do in the Istio support branches. Once Istio can move to an upstream Envoy release dependency we can hopefully stream line this process a bit.
